import { ArrowLeft, ArrowRight, LockKeyhole, Mail, Sparkles, UserRound } from "lucide-react";
import { useState, type FormEvent, type ReactNode } from "react";
import { Link, Navigate, useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../auth";
import { useTranslation } from "../i18n";
import { Button, Input, Label, Select, Spinner } from "../components/ui";

export function LoginPage() {
  const { user, login } = useAuth(); const { t } = useTranslation(); const navigate = useNavigate(); const location = useLocation();
  const [email, setEmail] = useState("freelancer13@archer.demo"); const [password, setPassword] = useState("ArcherDemo123!"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to="/app" replace />;
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await login(email, password); navigate((location.state as { from?: string } | null)?.from ?? "/app"); } catch (err) { setError(err instanceof Error ? err.message : t("auth.signInError")); } finally { setBusy(false); } }
  return <AuthFrame title={t("auth.welcome")} subtitle={t("auth.loginSubtitle")}><form onSubmit={submit} className="space-y-5"><div><Label htmlFor="email">{t("auth.email")}</Label><div className="relative"><Mail className="absolute left-3.5 top-3.5 text-slate-400" size={17} /><Input id="email" type="email" className="pl-10" value={email} onChange={(e) => setEmail(e.target.value)} required /></div></div><div><Label htmlFor="password">{t("auth.password")}</Label><div className="relative"><LockKeyhole className="absolute left-3.5 top-3.5 text-slate-400" size={17} /><Input id="password" type="password" className="pl-10" value={password} onChange={(e) => setPassword(e.target.value)} required /></div></div>{error && <p className="rounded-xl bg-red-50 px-3 py-2.5 text-sm font-semibold text-red-700">{error}</p>}<Button className="w-full" size="lg" disabled={busy}>{busy ? <Spinner /> : <>{t("auth.signIn")} <ArrowRight size={17} /></>}</Button></form><p className="mt-7 text-center text-sm text-slate-500">{t("auth.newToArcher")} <Link className="font-bold text-ink" to="/register">{t("auth.createAccount")}</Link></p></AuthFrame>;
}

export function RegisterPage() {
  const { user, register } = useAuth(); const { t } = useTranslation(); const navigate = useNavigate();
  const [form, setForm] = useState({ displayName: "", email: "", password: "", role: "FREELANCER" as "CLIENT" | "FREELANCER", defaultCurrency: "USD" as "USD" | "MMK" }); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  if (user) return <Navigate to="/app" replace />;
  const set = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await register(form); navigate("/app"); } catch (err) { setError(err instanceof Error ? err.message : t("auth.registerError")); } finally { setBusy(false); } }
  return <AuthFrame title={t("auth.registerTitle")} subtitle={t("auth.registerSubtitle")}><form onSubmit={submit} className="space-y-4"><div><Label htmlFor="displayName">{t("auth.name")}</Label><div className="relative"><UserRound className="absolute left-3.5 top-3.5 text-slate-400" size={17} /><Input id="displayName" className="pl-10" placeholder="e.g. Thiri Aung" value={form.displayName} onChange={(e) => set("displayName", e.target.value)} required /></div></div><div><Label htmlFor="email">{t("auth.email")}</Label><Input id="email" type="email" placeholder="you@example.com" value={form.email} onChange={(e) => set("email", e.target.value)} required /></div><div><Label htmlFor="password">{t("auth.password")}</Label><Input id="password" type="password" minLength={8} placeholder={t("auth.atLeast")} value={form.password} onChange={(e) => set("password", e.target.value)} required /></div><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="role">{t("auth.role")}</Label><Select id="role" value={form.role} onChange={(e) => set("role", e.target.value)}><option value="FREELANCER">{t("auth.findWork")}</option><option value="CLIENT">{t("auth.hireTalent")}</option></Select></div><div><Label htmlFor="currency">{t("auth.currency")}</Label><Select id="currency" value={form.defaultCurrency} onChange={(e) => set("defaultCurrency", e.target.value)}><option value="USD">USD</option><option value="MMK">MMK</option></Select></div></div>{error && <p className="rounded-xl bg-red-50 px-3 py-2.5 text-sm font-semibold text-red-700">{error}</p>}<Button className="w-full" size="lg" disabled={busy}>{busy ? <Spinner /> : <>{t("auth.createAccountButton")} <ArrowRight size={17} /></>}</Button></form><p className="mt-7 text-center text-sm text-slate-500">{t("auth.alreadyHave")} <Link className="font-bold text-ink" to="/login">{t("auth.signIn")}</Link></p></AuthFrame>;
}

function AuthFrame({ title, subtitle, children }: { title: string; subtitle: string; children: ReactNode }) { const { t } = useTranslation(); return <main className="flex min-h-[calc(100vh-80px)] items-center justify-center bg-cream px-5 py-12"><div className="w-full max-w-md"><Link to="/" className="mb-10 flex items-center justify-center gap-2 text-lg font-black text-ink"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-500"><Sparkles size={18} /></span>Archer</Link><div className="rounded-3xl border border-slate-200/80 bg-white p-6 shadow-soft sm:p-8"><Link to="/" className="mb-8 inline-flex items-center gap-1.5 text-xs font-bold text-slate-400"><ArrowLeft size={14} /> {t("common.backHome")}</Link><h1 className="text-3xl font-black tracking-tight text-ink">{title}</h1><p className="mt-2 text-sm leading-6 text-slate-500">{subtitle}</p><div className="mt-7">{children}</div></div></div></main>; }
