import { ArrowRight, Check, Compass, ShieldCheck, Sparkles, Users, WalletCards } from "lucide-react";
import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import { useTranslation } from "../i18n";
import { Button, Card } from "../components/ui";

export function HomePage() {
  const { t } = useTranslation();
  return <div><section className="overflow-hidden bg-cream"><div className="mx-auto grid max-w-7xl gap-14 px-5 py-20 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:py-28"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-amber-200 bg-amber-50 px-3 py-1.5 text-xs font-bold text-amber-700"><Sparkles size={14} /> {t("home.badge")}</div><h1 className="max-w-3xl text-5xl font-black leading-[1.03] tracking-[-.05em] text-ink sm:text-6xl lg:text-7xl">{t("home.heroTitle")}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">{t("home.heroText")}</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/jobs"><Button size="lg">{t("home.explore")} <ArrowRight size={17} /></Button></Link><Link to="/register"><Button variant="outline" size="lg">{t("home.join")}</Button></Link></div><div className="mt-10 flex flex-wrap gap-5 text-sm text-slate-500"><span className="flex items-center gap-2"><Check size={16} className="text-ocean-500" /> {t("home.noPayments")}</span><span className="flex items-center gap-2"><Check size={16} className="text-ocean-500" /> USD + MMK</span></div></div><div className="relative"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-amber-100 blur-3xl" /><Card className="relative border-0 bg-ink p-6 text-white"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-amber-300">Archer pulse</p><p className="mt-2 text-2xl font-black">Work, in motion.</p></div><Compass className="text-amber-300" /></div><div className="mt-8 space-y-3">{[["Brand identity for a new café", "USD 800 — 1,200", "Design"], ["React Native field app", "MMK 1,500,000 — 2,400,000", "Development"], ["Launch content system", "USD 450 — 700", "Writing"]].map(([title, amount, category]) => <div key={title} className="rounded-2xl border border-white/10 bg-white/5 p-4"><div className="flex items-start justify-between gap-4"><div><p className="font-bold">{title}</p><p className="mt-1 text-sm text-slate-400">{amount}</p></div><span className="rounded-full bg-amber-400/15 px-2 py-1 text-[10px] font-bold uppercase text-amber-300">{category}</span></div></div>)}</div></Card></div></div></section><section className="bg-white px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-ocean-600">{t("home.builtFor")}</p><h2 className="mt-3 text-3xl font-black tracking-tight text-ink sm:text-4xl">{t("home.simpleSide")}</h2><div className="mt-10 grid gap-5 md:grid-cols-3"><Feature icon={<Users />} title={t("home.findPeople")} text={t("home.findPeopleText")} /><Feature icon={<ShieldCheck />} title={t("home.workClarity")} text={t("home.workClarityText")} /><Feature icon={<WalletCards />} title={t("home.keepFlexible")} text={t("home.keepFlexibleText")} /></div></div></section></div>;
}

function Feature({ icon, title, text }: { icon: ReactNode; title: string; text: string }) { return <Card className="border-slate-200/70 p-6 shadow-none"><div className="mb-5 flex h-11 w-11 items-center justify-center rounded-xl bg-ocean-50 text-ocean-600">{icon}</div><h3 className="text-lg font-black text-ink">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></Card>; }
