import { ArrowRight, CalendarDays, ChevronLeft, ChevronRight, Filter, MapPin, Search, Star, Users, X } from "lucide-react";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useAuth } from "../auth";
import { useTranslation } from "../i18n";
import { api } from "../lib/api";
import { formatDate, formatMoney } from "../lib/utils";
import type { Job } from "../types";
import { Avatar, Badge, Button, Card, Input, Label, Select, Spinner, Textarea } from "../components/ui";

const categories = ["Web Development", "Mobile Development", "Design", "Writing", "Marketing", "Data & Analytics"];

export function JobsPage() {
  const { t } = useTranslation(); const [term, setTerm] = useState(""); const [q, setQ] = useState(""); const [category, setCategory] = useState(""); const [currency, setCurrency] = useState(""); const [page, setPage] = useState(1); const params = new URLSearchParams({ page: String(page), pageSize: "9" }); if (q) params.set("q", q); if (category) params.set("category", category); if (currency) params.set("currency", currency);
  const query = useQuery({ queryKey: ["jobs", params.toString()], queryFn: () => api.jobs(`?${params.toString()}`) });
  return <div><section className="bg-cream"><div className="mx-auto max-w-7xl px-5 py-12 lg:px-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-ocean-600">{t("jobs.open")}</p><div className="mt-3 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><h1 className="text-4xl font-black tracking-tight text-ink">{t("jobs.title")}</h1><p className="mt-2 text-slate-500">{t("jobs.subtitle")}</p></div><Link to="/register"><Button variant="secondary">{t("jobs.joinFreelancer")} <ArrowRight size={16} /></Button></Link></div><form className="mt-8 flex flex-col gap-3 md:flex-row" onSubmit={(e) => { e.preventDefault(); setQ(term); setPage(1); }}><div className="relative flex-1"><Search className="absolute left-4 top-3.5 text-slate-400" size={18} /><Input value={term} onChange={(e) => setTerm(e.target.value)} className="h-12 pl-11" placeholder={t("jobs.searchPlaceholder")} /></div><Select className="h-12 md:w-48" value={category} onChange={(e) => { setCategory(e.target.value); setPage(1); }}><option value="">{t("jobs.allCategories")}</option>{categories.map((item) => <option key={item}>{item}</option>)}</Select><Select className="h-12 md:w-36" value={currency} onChange={(e) => { setCurrency(e.target.value); setPage(1); }}><option value="">{t("jobs.anyCurrency")}</option><option>USD</option><option>MMK</option></Select><Button size="lg">{t("common.search")}</Button></form></div></section><main className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="mb-5 flex justify-between text-sm text-slate-500"><span>{query.data ? t("jobs.projects", { count: query.data.meta.total }) : t("jobs.loading")}</span><span className="flex items-center gap-1 text-xs font-semibold"><Filter size={14} /> {t("jobs.newest")}</span></div>{query.isLoading ? <Loading /> : query.isError ? <Empty title={t("jobs.apiUnavailable")} text={t("jobs.apiUnavailableText")} /> : query.data?.data.length ? <><div className="grid gap-5 lg:grid-cols-3">{query.data.data.map((job) => <JobCard key={job.id} job={job} />)}</div><div className="mt-8 flex items-center justify-center gap-3"><Button size="sm" variant="outline" disabled={page <= 1} onClick={() => setPage(page - 1)}><ChevronLeft size={15} /> {t("common.previous")}</Button><span className="text-xs font-bold">{t("common.pageOf", { page, total: query.data.meta.totalPages })}</span><Button size="sm" variant="outline" disabled={page >= query.data.meta.totalPages} onClick={() => setPage(page + 1)}>{t("common.next")} <ChevronRight size={15} /></Button></div></> : <Empty title={t("jobs.noMatch")} text={t("jobs.noMatchText")} />}</main></div>;
}

function JobCard({ job }: { job: Job }) { const { t } = useTranslation(); return <Link to={`/jobs/${job.id}`}><Card className="h-full p-5 transition hover:-translate-y-1 hover:border-amber-300"><div className="flex justify-between gap-3"><Badge tone="blue">{job.category}</Badge><span className="text-xs text-slate-400">{formatDate(job.createdAt)}</span></div><h2 className="mt-5 line-clamp-2 text-lg font-black leading-6 text-ink">{job.title}</h2><p className="mt-2 line-clamp-3 text-sm leading-6 text-slate-500">{job.description}</p><div className="mt-5 flex flex-wrap gap-1.5">{job.skills.slice(0, 3).map(({ skill }) => <span key={skill.id} className="rounded-md bg-slate-100 px-2 py-1 text-[11px] font-semibold text-slate-500">{skill.name}</span>)}</div><div className="mt-6 flex items-end justify-between border-t border-slate-100 pt-4"><div><p className="text-xs text-slate-400">{job.budgetType === "HOURLY" ? t("jobs.hourlyBudget") : t("jobs.projectBudget")}</p><p className="mt-1 text-sm font-black text-ink">{formatMoney(job.budgetMinMinor, job.currency)} – {formatMoney(job.budgetMaxMinor, job.currency)}</p></div><div className="text-right"><p className="flex items-center justify-end gap-1 text-xs text-slate-400"><Users size={13} /> {job._count?.proposals ?? 0}</p><p className="mt-1 flex items-center justify-end gap-1 text-xs text-slate-500"><MapPin size={13} /> {job.locationMode.toLowerCase()}</p></div></div></Card></Link>; }

export function JobDetailPage() {
  const { t } = useTranslation(); const { jobId } = useParams(); const { user } = useAuth(); const [open, setOpen] = useState(false); const query = useQuery({ queryKey: ["job", jobId], queryFn: () => api.job(jobId!), enabled: Boolean(jobId) });
  if (query.isLoading) return <div className="mx-auto max-w-5xl px-5 py-16"><Spinner /></div>; if (query.isError || !query.data) return <div className="mx-auto max-w-5xl px-5 py-16"><Empty title={t("jobs.projectNotFound")} text={t("jobs.projectNotFoundText")} /></div>;
  const job = query.data.data; return <main className="bg-cream"><div className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><Link to="/jobs" className="text-sm font-bold text-slate-500">← {t("common.backProjects")}</Link><div className="mt-8 grid gap-7 lg:grid-cols-[1fr_360px]"><div><div className="flex gap-2"><Badge tone="blue">{job.category}</Badge><Badge tone={job.status === "OPEN" ? "green" : "slate"}>{job.status}</Badge></div><h1 className="mt-5 text-4xl font-black tracking-tight text-ink sm:text-5xl">{job.title}</h1><div className="mt-5 flex flex-wrap gap-5 text-sm text-slate-500"><span className="flex items-center gap-2"><CalendarDays size={16} /> {t("jobs.posted", { date: formatDate(job.createdAt) })}</span><span className="flex items-center gap-2"><MapPin size={16} /> {job.locationMode.toLowerCase()}</span><span className="flex items-center gap-2"><Users size={16} /> {t("jobs.proposals", { count: job._count?.proposals ?? 0 })}</span></div><Card className="mt-8 p-6 shadow-none"><h2 className="text-lg font-black">{t("jobs.about")}</h2><p className="mt-4 whitespace-pre-line text-sm leading-7 text-slate-600">{job.description}</p><h3 className="mt-8 text-sm font-black">{t("jobs.skillsNeeded")}</h3><div className="mt-3 flex flex-wrap gap-2">{job.skills.map(({ skill }) => <span key={skill.id} className="rounded-lg bg-ocean-50 px-3 py-2 text-xs font-bold text-ocean-600">{skill.name}</span>)}</div></Card></div><Card className="h-fit p-6"><p className="text-xs font-bold uppercase tracking-[.15em] text-slate-400">{t("jobs.projectBudget")}</p><p className="mt-3 text-2xl font-black">{formatMoney(job.budgetMinMinor, job.currency)} – {formatMoney(job.budgetMaxMinor, job.currency)}</p><p className="mt-1 text-sm text-slate-500">{job.budgetType === "HOURLY" ? t("jobs.hourlyEngagement") : t("jobs.fixedPrice")}</p><div className="my-6 border-t border-slate-100" /><div className="flex items-center gap-3"><Avatar name={job.client.displayName} image={job.client.avatarUrl} /><div><p className="text-sm font-bold">{job.client.displayName}</p><p className="flex items-center gap-1 text-xs text-slate-400"><Star size={12} className="fill-amber-400 text-amber-400" /> {job.client.ratingAverage.toFixed(1)} ({job.client.ratingCount})</p></div></div>{user?.role === "FREELANCER" ? <Button className="mt-6 w-full" size="lg" disabled={job.status !== "OPEN"} onClick={() => setOpen(true)}>{t("jobs.submitProposal")}</Button> : !user ? <Link to="/login" state={{ from: `/jobs/${job.id}` }}><Button className="mt-6 w-full" size="lg">{t("jobs.signInToPropose")}</Button></Link> : <p className="mt-6 rounded-xl bg-slate-50 p-3 text-center text-xs font-semibold text-slate-500">{t("jobs.freelancerOnly")}</p>}</Card></div></div>{open && <ProposalModal job={job} close={() => setOpen(false)} />}</main>;
}

function ProposalModal({ job, close }: { job: Job; close: () => void }) { const { t } = useTranslation(); const client = useQueryClient(); const [letter, setLetter] = useState(""); const [amount, setAmount] = useState(job.currency === "USD" ? job.budgetMinMinor / 100 : job.budgetMinMinor); const [days, setDays] = useState(14); const mutation = useMutation({ mutationFn: () => api.createProposal(job.id, { coverLetter: letter, proposedAmountMinor: Math.round(amount * (job.currency === "USD" ? 100 : 1)), currency: job.currency, estimatedDays: days }), onSuccess: () => { client.invalidateQueries({ queryKey: ["proposals"] }); close(); } }); return <div className="fixed inset-0 z-50 flex items-end justify-center bg-ink/50 p-0 sm:items-center sm:p-5"><div className="w-full max-w-xl rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex justify-between"><div><p className="text-xs font-bold uppercase tracking-[.15em] text-ocean-600">{t("jobs.yourProposal")}</p><h2 className="mt-2 text-2xl font-black">{job.title}</h2></div><button aria-label={t("common.cancel")} onClick={close}><X /></button></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div><Label htmlFor="amount">{t("jobs.amount", { currency: job.currency })}</Label><Input id="amount" type="number" min="1" value={amount} onChange={(e) => setAmount(Number(e.target.value))} /></div><div><Label htmlFor="days">{t("jobs.estimatedDays")}</Label><Input id="days" type="number" min="1" value={days} onChange={(e) => setDays(Number(e.target.value))} /></div></div><div className="mt-4"><Label htmlFor="letter">{t("jobs.coverLetter")}</Label><Textarea id="letter" value={letter} onChange={(e) => setLetter(e.target.value)} placeholder={t("jobs.coverLetterPlaceholder")} /></div>{mutation.error && <p className="mt-3 text-sm font-semibold text-red-600">{mutation.error.message}</p>}<div className="mt-5 flex justify-end gap-3"><Button variant="ghost" onClick={close}>{t("common.cancel")}</Button><Button disabled={mutation.isPending || letter.length < 30} onClick={() => mutation.mutate()}>{mutation.isPending ? <Spinner /> : t("jobs.sendProposal")}</Button></div></div></div>; }

export function Empty({ title, text }: { title: string; text: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><Filter className="mx-auto text-slate-300" size={28} /><h2 className="mt-4 text-lg font-black">{title}</h2><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">{text}</p></div>; }
function Loading() { return <div className="grid gap-5 lg:grid-cols-3">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-80 animate-pulse rounded-2xl bg-slate-200" />)}</div>; }
