import type { ButtonHTMLAttributes, InputHTMLAttributes, ReactNode, TextareaHTMLAttributes } from "react";
import { cn, initials } from "../lib/utils";
export function Button({ className, variant = "primary", size = "md", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "outline" | "ghost" | "danger"; size?: "sm" | "md" | "lg" }) { return <button className={cn("inline-flex items-center justify-center gap-2 rounded-xl font-semibold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-amber-500 disabled:cursor-not-allowed disabled:opacity-50", variant === "primary" && "bg-ink text-white hover:bg-ink/90", variant === "secondary" && "bg-amber-500 text-ink hover:bg-amber-600", variant === "outline" && "border border-slate-200 bg-white text-ink hover:bg-slate-50", variant === "ghost" && "text-slate-600 hover:bg-slate-100", variant === "danger" && "bg-red-50 text-red-700 hover:bg-red-100", size === "sm" && "px-3 py-2 text-xs", size === "md" && "px-4 py-2.5 text-sm", size === "lg" && "px-5 py-3 text-sm", className)} {...props} />; }
export function Input({ className, ...props }: InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("h-11 w-full rounded-xl border border-slate-200 bg-white px-3.5 text-sm text-ink outline-none transition placeholder:text-slate-400 focus:border-amber-500 focus:ring-4 focus:ring-amber-500/10", className)} {...props} />; }
export function Textarea({ className, ...props }: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea className={cn("min-h-32 w-full resize-y rounded-xl border border-slate-200 bg-white px-3.5 py-3 text-sm text-ink outline-none transition placeholder:text-slate-400 focus:border-amber-500 focus:ring-4 focus:ring-amber-500/10", className)} {...props} />; }
export function Select({ className, children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className={cn("h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm text-ink outline-none focus:border-amber-500", className)} {...props}>{children}</select>; }
export function Label({ children, htmlFor }: { children: ReactNode; htmlFor?: string }) { return <label htmlFor={htmlFor} className="mb-2 block text-sm font-semibold text-slate-700">{children}</label>; }
export function Card({ children, className }: { children: ReactNode; className?: string }) { return <section className={cn("rounded-2xl border border-slate-200/80 bg-white shadow-soft", className)}>{children}</section>; }
export function Badge({ children, tone = "slate" }: { children: ReactNode; tone?: "slate" | "amber" | "green" | "blue" | "red" }) { return <span className={cn("inline-flex items-center rounded-full px-2.5 py-1 text-[11px] font-bold uppercase tracking-wide", tone === "slate" && "bg-slate-100 text-slate-600", tone === "amber" && "bg-amber-100 text-amber-700", tone === "green" && "bg-emerald-100 text-emerald-700", tone === "blue" && "bg-ocean-100 text-ocean-600", tone === "red" && "bg-red-100 text-red-700")}>{children}</span>; }
export function Avatar({ name, image, size = "md" }: { name: string; image?: string | null; size?: "sm" | "md" | "lg" }) { return image ? <img src={image} alt={name} className={cn("rounded-full object-cover", size === "sm" && "h-8 w-8", size === "md" && "h-10 w-10", size === "lg" && "h-16 w-16")} /> : <div className={cn("flex shrink-0 items-center justify-center rounded-full bg-amber-100 font-bold text-amber-700", size === "sm" && "h-8 w-8 text-[10px]", size === "md" && "h-10 w-10 text-xs", size === "lg" && "h-16 w-16 text-base")}>{initials(name)}</div>; }
export function Spinner() { return <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />; }
