import type { Contract, Conversation, Job, ListMeta, Message, Notification, Portfolio, Proposal, Review, Session, User } from "../types";
const API_URL = import.meta.env.VITE_API_URL ?? "http://localhost:3000/api/v1";
const KEY = "archer_session";
export function getSession(): Session | null { const value = localStorage.getItem(KEY); if (!value) return null; try { return JSON.parse(value) as Session; } catch { localStorage.removeItem(KEY); return null; } }
export function setSession(value: Session | null) { if (value) localStorage.setItem(KEY, JSON.stringify(value)); else localStorage.removeItem(KEY); }
async function refresh() { const current = getSession(); if (!current?.refreshToken) return false; const response = await fetch(`${API_URL}/auth/refresh`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ refreshToken: current.refreshToken }) }); if (!response.ok) return false; const payload = await response.json() as { data: Pick<Session, "accessToken" | "refreshToken"> }; setSession({ ...current, ...payload.data }); return true; }
export async function apiFetch<T>(path: string, options: RequestInit = {}, retry = true): Promise<T> { const current = getSession(); const headers = new Headers(options.headers); if (!(options.body instanceof FormData)) headers.set("Content-Type", "application/json"); if (current?.accessToken) headers.set("Authorization", `Bearer ${current.accessToken}`); const response = await fetch(`${API_URL}${path}`, { ...options, headers }); if (response.status === 401 && retry && await refresh()) return apiFetch<T>(path, options, false); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: { message?: string; fields?: Record<string, string[]> } } | null; const error = new Error(body?.error?.message ?? "Something went wrong"); Object.assign(error, { status: response.status, fields: body?.error?.fields }); throw error; } return response.status === 204 ? undefined as T : response.json() as Promise<T>; }
export const api = {
  login: (body: { email: string; password: string }) => apiFetch<{ data: Session }>("/auth/login", { method: "POST", body: JSON.stringify(body) }),
  register: (body: { email: string; password: string; displayName: string; role: "CLIENT" | "FREELANCER"; defaultCurrency: "USD" | "MMK" }) => apiFetch<{ data: Session }>("/auth/register", { method: "POST", body: JSON.stringify(body) }),
  me: () => apiFetch<{ data: User }>("/auth/me"), updateMe: (body: unknown) => apiFetch<{ data: User }>("/auth/me", { method: "PATCH", body: JSON.stringify(body) }), logout: (refreshToken: string) => apiFetch<void>("/auth/logout", { method: "POST", body: JSON.stringify({ refreshToken }) }, false),
  changePassword: (body: { currentPassword: string; newPassword: string }) => apiFetch<void>("/auth/change-password", { method: "POST", body: JSON.stringify(body) }),
  jobs: (query = "") => apiFetch<{ data: Job[]; meta: ListMeta }>(`/jobs${query}`), mineJobs: (query = "") => apiFetch<{ data: Job[]; meta: ListMeta }>(`/jobs/mine${query}`), job: (id: string) => apiFetch<{ data: Job }>(`/jobs/${id}`), createJob: (body: unknown) => apiFetch<{ data: Job }>("/jobs", { method: "POST", body: JSON.stringify(body) }),
  updateJob: (id: string, body: unknown) => apiFetch<{ data: Job }>(`/jobs/${id}`, { method: "PATCH", body: JSON.stringify(body) }),
  updateJobStatus: (id: string, status: string) => apiFetch<{ data: Job }>(`/jobs/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }),
  profiles: (query = "") => apiFetch<{ data: User[]; meta: ListMeta }>(`/profiles${query}`), profile: (id: string) => apiFetch<{ data: User }>(`/profiles/${id}`), createPortfolio: (body: unknown) => apiFetch<{ data: Portfolio }>("/profiles/me/portfolio", { method: "POST", body: JSON.stringify(body) }), deletePortfolio: (id: string) => apiFetch<void>(`/profiles/me/portfolio/${id}`, { method: "DELETE" }),
  proposals: (query = "") => apiFetch<{ data: Proposal[]; meta: ListMeta }>(`/proposals${query}`), createProposal: (jobId: string, body: unknown) => apiFetch<{ data: Proposal }>(`/proposals/jobs/${jobId}`, { method: "POST", body: JSON.stringify(body) }), withdrawProposal: (id: string) => apiFetch<{ data: Proposal }>(`/proposals/${id}/withdraw`, { method: "POST" }), acceptProposal: (id: string) => apiFetch<{ data: Contract }>(`/proposals/${id}/accept`, { method: "POST" }), shortlistProposal: (id: string) => apiFetch<{ data: Proposal }>(`/proposals/${id}/shortlist`, { method: "POST" }), rejectProposal: (id: string) => apiFetch<{ data: Proposal }>(`/proposals/${id}/reject`, { method: "POST" }),
  contracts: () => apiFetch<{ data: Contract[] }>("/contracts"), contract: (id: string) => apiFetch<{ data: Contract }>(`/contracts/${id}`), updateContractStatus: (id: string, status: string) => apiFetch<{ data: Contract }>(`/contracts/${id}/status`, { method: "PATCH", body: JSON.stringify({ status }) }), createReview: (contractId: string, body: unknown) => apiFetch<{ data: Review }>(`/reviews/contracts/${contractId}`, { method: "POST", body: JSON.stringify(body) }),
  conversations: () => apiFetch<{ data: Conversation[] }>("/conversations"), conversation: (id: string) => apiFetch<{ data: Conversation }>(`/conversations/${id}`), createConversation: (body: unknown) => apiFetch<{ data: Conversation }>("/conversations", { method: "POST", body: JSON.stringify(body) }), sendMessage: (id: string, body: string) => apiFetch<{ data: Message }>(`/conversations/${id}/messages`, { method: "POST", body: JSON.stringify({ body }) }), notifications: () => apiFetch<{ data: Notification[] }>("/notifications"), markNotification: (id: string) => apiFetch<void>(`/notifications/${id}/read`, { method: "POST" }), markAllNotifications: () => apiFetch<void>("/notifications/read-all", { method: "POST" })
};
